Repository adaptlearning/adapt-contrib-confidenceSlider, pull requests merged in 2023-03, with the labels that each got.

#80 New: use native slider instead of rangeslider (fixes #79)
  README.md
  example.json
  js/ConfidenceSliderModel.js
  js/ConfidenceSliderView.js
  less/confidenceSlider.less
  libraries/rangeslider.js
  templates/confidenceSlider.jsx
Labels: enhancement

#90 Update: _buttons ariaLabel amended as per other question components (fixes #81)
  example.json
Labels: accessibility

#92 Fix: _globals schema nesting
  schema/component.schema.json
  schema/course.schema.json
Labels: bug

#95 Fix: Fill styling for sliders (fixes #94)
  templates/confidenceSlider.jsx
Labels: bug
